'use strict';
// services/monthEndScheduler.js
//
// In-process cron scheduler that auto-creates and auto-generates a payroll run
// shortly after each month ends.
//
// Trigger time: 03:00 Asia/Kolkata on the 1st of each month (configurable via
// MONTH_END_CRON_SCHEDULE). This fires for the month that just ended — e.g.
// on 2026-08-01 it creates/generates the July 2026 run.
//
// Design constraints:
//   • Safe under PM2 fork mode with instances: 1 — no distributed locking needed.
//     If instances is ever changed to >1, this scheduler MUST be moved to a
//     dedicated worker or guarded with a distributed lock.
//   • Never crashes the process — all errors are caught and logged.
//   • Idempotent — the unique (month, year) index prevents double-creation; if an
//     Admin already created the run manually the scheduler skips gracefully.
//   • Finalize and mark-paid remain manual Admin actions — the auto run always
//     produces a draft for human review before money moves.
//   • Missed cron windows (e.g. deploy at 03:00) can be caught up via
//     POST /api/payroll-runs/auto-generate/trigger (requireAdmin).

const cron = require('node-cron');
const {
    createPayrollRun,
    generatePayrollRun,
    DuplicatePayrollRunError,
} = require('./payrollRunService');
const { audit }  = require('./auditLogger');
const { logger } = require('../utils/logger');

// ─── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Returns the month and year of the calendar month that just ended relative to
 * the given reference date (defaults to "now").
 *
 * Uses setDate(1) before subtracting a month to avoid month-length rollover bugs
 * (e.g. 31 March - 1 month must not land on 3 March instead of 28/29 February).
 *
 * Examples:
 *   referenceDate = 2026-08-01 → { month: 7, year: 2026 }   (July 2026 just ended)
 *   referenceDate = 2026-01-01 → { month: 12, year: 2025 }  (December 2025 just ended)
 *
 * @param {Date} [referenceDate]
 * @returns {{ month: number, year: number }}
 */
function getPreviousMonthYear(referenceDate = new Date()) {
    const d = new Date(referenceDate);
    d.setDate(1);           // anchor to 1st — avoids month-length rollover
    d.setMonth(d.getMonth() - 1);
    return { month: d.getMonth() + 1, year: d.getFullYear() };
}

// ─── Core job ─────────────────────────────────────────────────────────────────

/**
 * Creates and generates the payroll run for the previous calendar month.
 * Idempotent — safe to call multiple times; skips cleanly if a run already exists.
 *
 * @param {'cron'|'manual-catchup'} triggeredBy
 */
async function runMonthEndJob(triggeredBy = 'cron') {
    const { month, year } = getPreviousMonthYear();
    const label = `${year}-${String(month).padStart(2, '0')}`;

    logger.info(`[month-end-scheduler] Starting auto-generation for ${label} (trigger: ${triggeredBy})`);

    // ── Stage 1: Create draft run ────────────────────────────────────────────
    let run;
    try {
        run = await createPayrollRun({
            month,
            year,
            notes:      `Auto-generated by month-end scheduler (${triggeredBy})`,
            actorId:    null,
            actorEmail: 'system@scheduler',
            source:     'auto',
        });
    } catch (err) {
        if (err instanceof DuplicatePayrollRunError) {
            // An Admin (or a previous cron fire) already created this run — skip silently.
            logger.info(`[month-end-scheduler] Run for ${label} already exists — skipping creation`);
            await audit({
                action:           'PAYROLL_RUN_AUTO_SKIPPED',
                req:              null,
                subject:          label,
                details:          { reason: 'run already exists', trigger: triggeredBy },
                success:          true,
                performedByEmail: 'system@scheduler',
            });
            return;
        }

        // Unexpected error — log and bail; do NOT throw (never crash the process from cron)
        logger.error(`[month-end-scheduler] Failed to create run for ${label}: ${err.message}`, { stack: err.stack });
        await audit({
            action:           'PAYROLL_RUN_AUTO_FAILED',
            req:              null,
            subject:          label,
            details:          { stage: 'create', error: err.message, trigger: triggeredBy },
            success:          false,
            errorMessage:     err.message,
            performedByEmail: 'system@scheduler',
        });
        return;
    }

    await audit({
        action:           'PAYROLL_RUN_AUTO_CREATED',
        req:              null,
        subject:          label,
        details:          { payrollRunId: run._id, trigger: triggeredBy },
        success:          true,
        performedByEmail: 'system@scheduler',
    });

    // ── Stage 2: Generate all salary slips ──────────────────────────────────
    try {
        const result = await generatePayrollRun(run._id, {
            actorId:    null,
            actorEmail: 'system@scheduler',
            source:     'auto',
        });

        logger.info(
            `[month-end-scheduler] Generated ${label}: ` +
            `${result.success.length} succeeded, ${result.failed.length} failed`
        );

        await audit({
            action:           'PAYROLL_RUN_AUTO_GENERATED',
            req:              null,
            subject:          label,
            details:          {
                payrollRunId:  run._id,
                successCount:  result.success.length,
                failedCount:   result.failed.length,
                totalGross:    result.totalGross,
                totalNet:      result.totalNet,
                employeeCount: result.employeeCount,
                // Include per-employee failures so an Admin can diagnose at a glance
                // via GET /api/audit-logs without opening the run itself.
                failed:        result.failed,
                trigger:       triggeredBy,
            },
            success:          result.failed.length === 0,
            errorMessage:     result.failed.length > 0
                ? `${result.failed.length} slip(s) failed — see details`
                : null,
            performedByEmail: 'system@scheduler',
        });

        // Run stays in status: 'draft' — Admin reviews totals and calls finalize/mark-paid.

    } catch (err) {
        logger.error(`[month-end-scheduler] Generation failed for ${label}: ${err.message}`, { stack: err.stack });
        await audit({
            action:           'PAYROLL_RUN_AUTO_FAILED',
            req:              null,
            subject:          label,
            details:          { stage: 'generate', payrollRunId: run._id, error: err.message, trigger: triggeredBy },
            success:          false,
            errorMessage:     err.message,
            performedByEmail: 'system@scheduler',
        });
        // Do not rethrow — never crash the process from a scheduled job.
    }
}

// ─── Scheduler bootstrap ──────────────────────────────────────────────────────

/**
 * Registers the month-end cron job.
 * Call this once after MongoDB connects, before app.listen().
 *
 * Env vars:
 *   MONTH_END_AUTO_GENERATE_ENABLED  — set to 'false' to disable entirely (e.g. staging)
 *   MONTH_END_CRON_SCHEDULE          — standard cron expression (default: '0 3 1 * *' = 03:00 on the 1st)
 *   TZ                               — timezone for schedule evaluation (default: 'Asia/Kolkata')
 *
 * PM2 safety note: this scheduler is safe only when instances: 1 / exec_mode: 'fork'.
 * If you ever change the PM2 config to cluster mode or instances > 1 you MUST add a
 * distributed lock (e.g. a DB-level mutex) before the createPayrollRun call, or move
 * this to a dedicated singleton worker process.
 */
function startMonthEndScheduler() {
    if (process.env.MONTH_END_AUTO_GENERATE_ENABLED === 'false') {
        logger.info('[month-end-scheduler] Disabled via MONTH_END_AUTO_GENERATE_ENABLED=false');
        return;
    }

    const schedule = process.env.MONTH_END_CRON_SCHEDULE || '0 3 1 * *';
    const timezone = process.env.TZ || 'Asia/Kolkata';

    if (!cron.validate(schedule)) {
        logger.error(`[month-end-scheduler] Invalid cron expression: "${schedule}" — scheduler NOT started`);
        return;
    }

    cron.schedule(schedule, () => {
        runMonthEndJob('cron').catch(err => {
            // Belt-and-suspenders: runMonthEndJob already catches everything internally,
            // but if it somehow throws (e.g. out-of-memory), catch here too.
            logger.error(`[month-end-scheduler] Unhandled error in runMonthEndJob: ${err.message}`, { stack: err.stack });
        });
    }, { timezone });

    logger.info(`[month-end-scheduler] Scheduled — expression: "${schedule}", timezone: "${timezone}"`);
}

module.exports = { startMonthEndScheduler, runMonthEndJob, getPreviousMonthYear };
