// backend/models/Holiday.js
const mongoose = require('mongoose');

const holidaySchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        trim: true,
        maxlength: 100,
    },
    date: {
        type: Date,
        required: function() {
            return !this.isTentative; // Date is required only if not tentative
        },
        default: null,
    },
    isTentative: {
        type: Boolean,
        default: false,
    },
    day: {
        type: String,
        trim: true,
        // Store day as provided (can be single or multiple days)
    },
    type: {
        type: String,
        enum: ['National', 'Regional', 'Company', 'Optional'],
        default: 'Company'
    },
    appliesTo: {
        type: String,
        enum: ['All', 'Department', 'Branch'],
        default: 'All'
    },
    leaveYearId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'LeaveYear',
        required: false, // Will be required after migration
        index: true
    },
    
    // === INTELLIGENT HOLIDAY ENGINE FIELDS ===
    
    // Calculation Type
    calculationType: {
        type: String,
        enum: ['FIXED', 'LUNAR', 'MANUAL'],
        default: 'MANUAL'
    },
    
    // For FIXED holidays (e.g., Republic Day = Jan 26)
    baseMonth: {
        type: Number,
        min: 1,
        max: 12,
        required: function() {
            return this.calculationType === 'FIXED';
        }
    },
    baseDate: {
        type: Number,
        min: 1,
        max: 31,
        required: function() {
            return this.calculationType === 'FIXED';
        }
    },
    
    // For LUNAR holidays (e.g., Holi, Diwali)
    indianHolidayCode: {
        type: String,
        uppercase: true,
        trim: true,
        required: function() {
            return this.calculationType === 'LUNAR';
        }
    },
    
    // Tracking Fields
    isAutoGenerated: {
        type: Boolean,
        default: false
    },
    isManuallyEdited: {
        type: Boolean,
        default: false
    },
    isLocked: {
        type: Boolean,
        default: false
    },
    sourceDatasetVersion: {
        type: String,
        trim: true
    },
    
    // Audit Trail
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    updatedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    editHistory: [{
        field: String,
        oldValue: mongoose.Schema.Types.Mixed,
        newValue: mongoose.Schema.Types.Mixed,
        editedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User'
        },
        editedAt: {
            type: Date,
            default: Date.now
        },
        reason: String
    }]
}, { timestamps: true });

// Compound index: unique date per leave year (only for non-tentative holidays with dates)
holidaySchema.index(
    { date: 1, leaveYearId: 1 }, 
    { 
        unique: true, 
        sparse: true,
        partialFilterExpression: { isTentative: false, date: { $ne: null } },
        name: 'unique_date_per_year'
    }
);

// Index for efficient active year queries
holidaySchema.index({ leaveYearId: 1, date: 1 });

// Index for type-based filtering within a year
holidaySchema.index({ leaveYearId: 1, type: 1 });

// Index for tentative holidays (one per name per year)
holidaySchema.index({ name: 1, isTentative: 1, leaveYearId: 1 }, { 
    unique: true, 
    partialFilterExpression: { isTentative: true },
    name: 'unique_tentative_per_year'
});

module.exports = mongoose.model('Holiday', holidaySchema);